### ISSUE TITLE
Should `Room.leave` call `registerEventHandler` by mistake?

### ISSUE THREAD

**Issue by kevinw** [4Players/odin-wrapper-swift#1]
Is this a copy-paste typo? `Room.leave` calls `registerEventHandler` where it looks like `unregisterEventHandler` is more appropriate.

https://github.com/4Players/odin-wrapper-swift/blob/ed2e68786a8ab3df2b4ae97c8b6c1be91a5001b0/Sources/Models/Room.swift#L198-L212

**Comment by svenpaulsen** [comment]
You're absolutely right. Apologies for not noticing this earlier! 😇
